### ISSUE TITLE
[LFLiveSession availableCameraDevices]是空数组

### ISSUE THREAD

**Issue by riceRound** [KKBOX/LFLiveKitMac#2]
NSArray *array = [LFLiveSession availableCameraDevices];
在MacBook Pro上运行Mac端的App，array一直是空数组

**Comment by zonble** [comment]
Mac app 其實有一項 Capabilities 的設置，在裡頭我們必須要勾選 Camera 以及 Microphone，讓用戶允許我們使用攝像頭以及麥克風，如果沒有設置的話，就會無法使用。請先檢查一下您是否做了這些設置。

![screen shot 2017-12-20 at 2 41 45 pm](https://user-images.githubusercontent.com/53011/34194626-9137489a-e594-11e7-968b-8e4c55d69b15.png)
