### ISSUE TITLE
推流后保存到本地无任何反应

### ISSUE THREAD

**Issue by riceRound** [KKBOX/LFLiveKitMac#3]
<img width="808" alt="2017-12-22 3 52 20" src="https://user-images.githubusercontent.com/8563154/34291287-8b1018e0-e736-11e7-8852-5898eb36c5ff.png">

输出信息如下：
2017-12-22 16:39:02.561780+0800 MacLiveStreaming[1529:27266] Unknown Window class (null) in Interface Builder file,
	 creating generic Window instead
2017-12-22 16:39:04.571407+0800 MacLiveStreaming[1529:27294] MicrophoneSource: startRunning
=================================================================
Main Thread Checker: UI API called on a background thread: -[NSView bounds]
PID: 1529, TID: 27294, Thread name: (none), Queue name: com.sunsetlakesoftware.GPUImage.openGLESContextQueue, QoS: 0
Backtrace:
4   MacLiveStreaming                    0x000000010009d59c -[GPUImageView maximumOutputSize] + 92
5   MacLiveStreaming                    0x000000010009d6fb -[GPUImageView sizeInPixels] + 91
6   MacLiveStreaming                    0x000000010009c964 -[GPUImageView recalculateViewGeometry] + 52
7   MacLiveStreaming                    0x000000010009d46a __37-[GPUImageView setInputSize:atIndex:]_block_invoke + 234
8   MacLiveStreaming                    0x000000010007a5ab runSynchronouslyOnVideoProcessingQueue + 123
9   MacLiveStreaming                    0x000000010009d360 -[GPUImageView setInputSize:atIndex:] + 176
10  MacLiveStreaming                    0x0000000100053c51 -[GPUImageFilter informTargetsAboutNewFrameAtTime:] + 865
11  MacLiveStreaming                    0x000000010004fbda -[GPUImageCropFilter newFrameReadyAtTime:atIndex:] + 138
12  MacLiveStreaming                    0x00000001000451f8 -[GPUImageAVCamera updateTargetsForVideoCameraUsingCacheTextureAtWidth:height:time:] + 1832
13  MacLiveStreaming                    0x00000001000454f2 -[GPUImageAVCamera processVideoSampleBuffer:] + 514
14  MacLiveStreaming                    0x0000000100045cf8 __71-[GPUImageAVCamera captureOutput:didOutputSampleBuffer:fromConnection:]_block_invoke.149 + 296
15  libdispatch.dylib                   0x00000001005c4cfe _dispatch_call_block_and_release + 12
16  libdispatch.dylib                   0x00000001005bb78c _dispatch_client_callout + 8
17  libdispatch.dylib                   0x00000001005d293f _dispatch_queue_serial_drain + 205
18  libdispatch.dylib                   0x00000001005c4aa2 _dispatch_queue_invoke + 1174
19  libdispatch.dylib                   0x00000001005bda0c _dispatch_root_queue_drain + 671
20  libdispatch.dylib                   0x00000001005bd71d _dispatch_worker_thread3 + 114
21  libsystem_pthread.dylib             0x00000001006327da _pthread_wqthread + 1299
22  libsystem_pthread.dylib             0x00000001006322b5 start_wqthread + 13
2017-12-22 16:39:04.714000+0800 MacLiveStreaming[1529:27294] [reports] Main Thread Checker: UI API called on a background thread: -[NSView bounds]
PID: 1529, TID: 27294, Thread name: (none), Queue name: com.sunsetlakesoftware.GPUImage.openGLESContextQueue, QoS: 0
Backtrace:
4   MacLiveStreaming                    0x000000010009d59c -[GPUImageView maximumOutputSize] + 92
5   MacLiveStreaming                    0x000000010009d6fb -[GPUImageView sizeInPixels] + 91
6   MacLiveStreaming                    0x000000010009c964 -[GPUImageView recalculateViewGeometry] + 52
7   MacLiveStreaming                    0x000000010009d46a __37-[GPUImageView setInputSize:atIndex:]_block_invoke + 234
8   MacLiveStreaming                    0x000000010007a5ab runSynchronouslyOnVideoProcessingQueue + 123
9   MacLiveStreaming                    0x000000010009d360 -[GPUImageView setInputSize:atIndex:] + 176
10  MacLiveStreaming                    0x0000000100053c51 -[GPUImageFilter informTargetsAboutNewFrameAtTime:] + 865
11  MacLiveStreaming                    0x000000010004fbda -[GPUImageCropFilter newFrameReadyAtTime:atIndex:] + 138
12  MacLiveStreaming                    0x00000001000451f8 -[GPUImageAVCamera updateTargetsForVideoCameraUsingCacheTextureAtWidth:height:time:] + 1832
13  MacLiveStreaming                    0x00000001000454f2 -[GPUImageAVCamera processVideoSampleBuffer:] + 514
14  MacLiveStreaming                    0x0000000100045cf8 __71-[GPUImageAVCamera captureOutput:didOutputSampleBuffer:fromConnection:]_block_invoke.149 + 296
15  libdispatch.dylib                   0x00000001005c4cfe _dispatch_call_block_and_release + 12
16  libdispatch.dylib                   0x00000001005bb78c _dispatch_client_callout + 8
17  libdispatch.dylib                   0x00000001005d293f _dispatch_queue_serial_drain + 205
18  libdispatch.dylib                   0x00000001005c4aa2 _dispatch_queue_invoke + 1174
19  libdispatch.dylib                   0x00000001005bda0c _dispatch_root_queue_drain + 671
20  libdispatch.dylib                   0x00000001005bd71d _dispatch_worker_thread3 + 114
21  libsystem_pthread.dylib             0x00000001006327da _pthread_wqthread + 1299
22  libsystem_pthread.dylib             0x00000001006322b5 start_wqthread + 13
=================================================================
Main Thread Checker: UI API called on a background thread: -[NSView convertSizeToBacking:]
PID: 1529, TID: 27294, Thread name: (none), Queue name: com.sunsetlakesoftware.GPUImage.openGLESContextQueue, QoS: 0
Backtrace:
4   MacLiveStreaming                    0x000000010009d5c9 -[GPUImageView maximumOutputSize] + 137
5   MacLiveStreaming                    0x000000010009d6fb -[GPUImageView sizeInPixels] + 91
6   MacLiveStreaming                    0x000000010009c964 -[GPUImageView recalculateViewGeometry] + 52
7   MacLiveStreaming                    0x000000010009d46a __37-[GPUImageView setInputSize:atIndex:]_block_invoke + 234
8   MacLiveStreaming                    0x000000010007a5ab runSynchronouslyOnVideoProcessingQueue + 123
9   MacLiveStreaming                    0x000000010009d360 -[GPUImageView setInputSize:atIndex:] + 176
10  MacLiveStreaming                    0x0000000100053c51 -[GPUImageFilter informTargetsAboutNewFrameAtTime:] + 865
11  MacLiveStreaming                    0x000000010004fbda -[GPUImageCropFilter newFrameReadyAtTime:atIndex:] + 138
12  MacLiveStreaming                    0x00000001000451f8 -[GPUImageAVCamera updateTargetsForVideoCameraUsingCacheTextureAtWidth:height:time:] + 1832
13  MacLiveStreaming                    0x00000001000454f2 -[GPUImageAVCamera processVideoSampleBuffer:] + 514
14  MacLiveStreaming                    0x0000000100045cf8 __71-[GPUImageAVCamera captureOutput:didOutputSampleBuffer:fromConnection:]_block_invoke.149 + 296
15  libdispatch.dylib                   0x00000001005c4cfe _dispatch_call_block_and_release + 12
16  libdispatch.dylib                   0x00000001005bb78c _dispatch_client_callout + 8
17  libdispatch.dylib                   0x00000001005d293f _dispatch_queue_serial_drain + 205
18  libdispatch.dylib                   0x00000001005c4aa2 _dispatch_queue_invoke + 1174
19  libdispatch.dylib                   0x00000001005bda0c _dispatch_root_queue_drain + 671
20  libdispatch.dylib                   0x00000001005bd71d _dispatch_worker_thread3 + 114
21  libsystem_pthread.dylib             0x00000001006327da _pthread_wqthread + 1299
22  libsystem_pthread.dylib             0x00000001006322b5 start_wqthread + 13
2017-12-22 16:39:04.837987+0800 MacLiveStreaming[1529:27294] [reports] Main Thread Checker: UI API called on a background thread: -[NSView convertSizeToBacking:]
PID: 1529, TID: 27294, Thread name: (none), Queue name: com.sunsetlakesoftware.GPUImage.openGLESContextQueue, QoS: 0
Backtrace:
4   MacLiveStreaming                    0x000000010009d5c9 -[GPUImageView maximumOutputSize] + 137
5   MacLiveStreaming                    0x000000010009d6fb -[GPUImageView sizeInPixels] + 91
6   MacLiveStreaming                    0x000000010009c964 -[GPUImageView recalculateViewGeometry] + 52
7   MacLiveStreaming                    0x000000010009d46a __37-[GPUImageView setInputSize:atIndex:]_block_invoke + 234
8   MacLiveStreaming                    0x000000010007a5ab runSynchronouslyOnVideoProcessingQueue + 123
9   MacLiveStreaming                    0x000000010009d360 -[GPUImageView setInputSize:atIndex:] + 176
10  MacLiveStreaming                    0x0000000100053c51 -[GPUImageFilter informTargetsAboutNewFrameAtTime:] + 865
11  MacLiveStreaming                    0x000000010004fbda -[GPUImageCropFilter newFrameReadyAtTime:atIndex:] + 138
12  MacLiveStreaming                    0x00000001000451f8 -[GPUImageAVCamera updateTargetsForVideoCameraUsingCacheTextureAtWidth:height:time:] + 1832
13  MacLiveStreaming                    0x00000001000454f2 -[GPUImageAVCamera processVideoSampleBuffer:] + 514
14  MacLiveStreaming                    0x0000000100045cf8 __71-[GPUImageAVCamera captureOutput:didOutputSampleBuffer:fromConnection:]_block_invoke.149 + 296
15  libdispatch.dylib                   0x00000001005c4cfe _dispatch_call_block_and_release + 12
16  libdispatch.dylib                   0x00000001005bb78c _dispatch_client_callout + 8
17  libdispatch.dylib                   0x00000001005d293f _dispatch_queue_serial_drain + 205
18  libdispatch.dylib                   0x00000001005c4aa2 _dispatch_queue_invoke + 1174
19  libdispatch.dylib                   0x00000001005bda0c _dispatch_root_queue_drain + 671
20  libdispatch.dylib                   0x00000001005bd71d _dispatch_worker_thread3 + 114
21  libsystem_pthread.dylib             0x00000001006327da _pthread_wqthread + 1299
22  libsystem_pthread.dylib             0x00000001006322b5 start_wqthread + 13
2017-12-22 16:39:11.802385+0800 MacLiveStreaming[1529:27355] USE LFHardwareAudioEncoder
2017-12-22 16:39:11.802544+0800 MacLiveStreaming[1529:27355] /Users/wangyuan/Library/Containers/com.viper.MacLiveStreaming/Data/Documents/IOSCamDemo_HW.aac
2017-12-22 16:39:11.819805+0800 MacLiveStreaming[1529:27299] USE LF264VideoEncoder
2017-12-22 16:39:11.819893+0800 MacLiveStreaming[1529:27299] /Users/wangyuan/Library/Containers/com.viper.MacLiveStreaming/Data/Documents/IOSCamDemo.h264
2017-12-22 16:39:11.921900+0800 MacLiveStreaming[1529:27299] GVA info: preferred scaler idx 0
2017-12-22 16:39:11.993804+0800 MacLiveStreaming[1529:27299] GVA info: preferred scaler idx 0

**Comment by zonble** [comment]
這個問題跟你前一個問題差不多，在於 Sandbox。

在 Mac 上，每個要上架的 App，都得要在 Sandbox 當中執行，你想要把資料直接儲存在 desktop 上，這個位置超過 sanbox 允許你存檔的範圍，請先看一下蘋果的相關文件：

https://developer.apple.com/library/content/documentation/Security/Conceptual/AppSandboxDesignGuide/AboutAppSandbox/AboutAppSandbox.html

對於 App 開發來說，這應該是很基礎的知識才對。如果您還不太熟悉 Mac 開發的一些基本的話，可能大家也不見得能夠幫得上什麼忙。

**Comment by riceRound** [comment]
感谢您的教诲，是我没有学好基础理论，打扰您了

发自我的 iPhone

在 2017年12月23日，02:47，Weizhong Yang <notifications@github.com<mailto:notifications@github.com>> 写道：


這個問題跟你前一個問題差不多，在於 Sandbox。

在 Mac 上，每個要上架的 App，都得要在 Sandbox 當中執行，你想要把資料直接儲存在 desktop 上，這個位置超過 sanbox 允許你存檔的範圍，請先看一下蘋果的相關文件：

https://developer.apple.com/library/content/documentation/Security/Conceptual/AppSandboxDesignGuide/AboutAppSandbox/AboutAppSandbox.html

對於 App 開發來說，這應該是很基礎的知識才對。如果您還不太熟悉 Mac 開發的一些基本的話，可能大家也不見得能夠幫得上什麼忙。
